# Minimal change to force Render redeploy
services:
  # Redis instance
  - type: redis
    name: audio-transcriber-redis
    ipAllowList: [] # only allow internal connections by default

  # Web service
  - type: web
    name: audio-transcriber
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 180 --worker-class gevent
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: audio-transcriber-redis
    autoDeploy: true

  # RQ worker service
  - type: worker
    name: audio-transcriber-rq-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: rq worker --url $REDIS_URL default
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: audio-transcriber-redis
